In [26]:
import json
import os
import random

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
data_path = "data/dataset/corpus.jsonl"
corpus_documents = []
corpus_documents_ids = []
with open(data_path, "r") as file:
    for line in file:
        data = json.loads(line)
        corpus_documents.append(data["text"])
        corpus_documents_ids.append(data["_id"])

corpus_documents_ids[0:5]

['1867825', '419610', '4614226', '4108603', '3744854']

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(corpus_documents)

In [24]:
document_index = corpus_documents_ids.index("4614226")
tfidf_representation = tfidf_matrix[document_index]
a = np.nonzero(np.array(tfidf_representation.toarray()))
np.array(tfidf_representation.toarray())[a]

array([0.12009248, 0.13712392, 0.17338543, 0.18353344, 0.2466042 ,
       0.20782878, 0.20617027, 0.24829981, 0.27342867, 0.14878987,
       0.31758786, 0.05750954, 0.07521727, 0.12691783, 0.04379337,
       0.15730779, 0.09580393, 0.06425652, 0.21724227, 0.15829103,
       0.15630983, 0.21075894, 0.25698353, 0.14989651, 0.17198681,
       0.26661405, 0.10626531, 0.09990259, 0.08397754, 0.13712392,
       0.16228345, 0.16827458])

In [28]:
query = "How does TF-IDF work?"

# Vectorize the query using the same TF-IDF vectorizer
query_vector = tfidf_vectorizer.transform([query])
query_vector.toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarities = cosine_similarity(query_vector, tfidf_matrix)

In [34]:
document_indices_sorted_by_similarity = cosine_similarities[0].argsort()[::-1]

# Get the corresponding similarity scores
similarity_scores_sorted = cosine_similarities[0][document_indices_sorted_by_similarity]
document_indices_sorted_by_similarity

array([ 255302, 1321829,   25413, ...,  958995,  958996,       0])

In [35]:
similarity_scores_sorted[0]

0.3988510691915165

In [31]:
num_top_documents = 5

# Retrieve the top N documents and their similarity scores
top_documents = [text_data[i] for i in document_indices_sorted_by_similarity[:num_top_documents]]
top_similarity_scores = similarity_scores_sorted[:num_top_documents]

# Present the results
for i, (document, similarity) in enumerate(zip(top_documents, top_similarity_scores), start=1):
    print(f"Rank {i}: Similarity Score = {similarity:.4f}")
    print(document)
    print()


NameError: name 'text_data' is not defined